###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/users

###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar

###

DELETE http://localhost:9080/demo-1.0-SNAPSHOT/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar

###

PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png'

< C:\projects\NIA_JEE_2023\example\demo\src\main\resources\avatar\eloise.png

--boundary--

###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/products

###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1

###

PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
    Content-Type: application/json

{
  "name": "NewCreated",
  "brand": "NewBrand"
}

###

DELETE http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1

###

PATCH http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
Content-Type: application/json

{
  "name": "UPDATED name",
  "brand": "UPDATED brand"
}

###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/products/837a3e70-f64b-4088-b834-4658a08253a2/items

###

PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1/items/ff327e8a-77c0-4f9b-90a2-89e16895d1e2
Content-Type: application/json

{
  "date": "2023-10-10"
}

###

GET http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1/items/ff327e8a-77c0-4f9b-90a2-89e16895d1e2

###

###

PATCH http://localhost:9080/demo-1.0-SNAPSHOT/api/products/837a3e70-f64b-4088-b834-4658a08253a2/items/ff327e8a-77c0-4f9b-90a2-89e16895d1e2
Content-Type: application/json

{
  "date": "2023-06-30"
}

###

DELETE http://localhost:9080/demo-1.0-SNAPSHOT/api/products/ff327e8a-77c0-4f9b-90a2-89e16895d1e1/items/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
